/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */
const universalEthAddress =
  "0x49D36570D4E46F48E99674BD3FCC84644DDD6B96F7C741B1562B82F9E004DC7";
const preDeployedContracts = {
  devnet: {
    Eth: {
      address: universalEthAddress,
      abi: [
        {
          type: "impl",
          name: "ERC20Impl",
          interface_name: "openzeppelin::token::erc20::interface::IERC20",
        },
        {
          name: "openzeppelin::token::erc20::interface::IERC20",
          type: "interface",
          items: [
            {
              name: "name",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "symbol",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "decimals",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "total_supply",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "balance_of",
              type: "function",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "allowance",
              type: "function",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "transfer",
              type: "function",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              name: "transfer_from",
              type: "function",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              name: "approve",
              type: "function",
              inputs: [
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          name: "ERC20CamelOnlyImpl",
          type: "impl",
          interface_name:
            "openzeppelin::token::erc20::interface::IERC20CamelOnly",
        },
        {
          type: "interface",
          name: "openzeppelin::token::erc20::interface::IERC20CamelOnly",
          items: [
            {
              name: "totalSupply",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "balanceOf",
              type: "function",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "transferFrom",
              type: "function",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          kind: "struct",
          name: "openzeppelin::token::erc20_v070::erc20::ERC20::Transfer",
          type: "event",
          members: [
            {
              kind: "data",
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              kind: "data",
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              kind: "data",
              name: "value",
              type: "core::integer::u256",
            },
          ],
        },
        {
          kind: "enum",
          name: "openzeppelin::token::erc20_v070::erc20::ERC20::Event",
          type: "event",
          variants: [
            {
              kind: "nested",
              name: "Transfer",
              type: "openzeppelin::token::erc20_v070::erc20::ERC20::Transfer",
            },
          ],
        },
      ],
    },
    ShaboyGames:{
      abi: [
        {
            "type": "impl",
            "name": "ExternalImplERC721",
            "interface_name": "nftcontract::checkforworking::IERC721"
        },
        {
            "type": "struct",
            "name": "core::integer::u256",
            "members": [
                {
                    "name": "low",
                    "type": "core::integer::u128"
                },
                {
                    "name": "high",
                    "type": "core::integer::u128"
                }
            ]
        },
        {
            "type": "interface",
            "name": "nftcontract::checkforworking::IERC721",
            "items": [
                {
                    "type": "function",
                    "name": "name",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "symbol",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "balance_of",
                    "inputs": [
                        {
                            "name": "account",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "owner_of",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "get_counter_id",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "allowed_erc20_address",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "price_of_token_id",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "token_title",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "mint_multi",
                    "inputs": [
                        {
                            "name": "token_name",
                            "type": "core::felt252"
                        },
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "list",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "price",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "buy_nft",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "amount",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": [
                {
                    "name": "name",
                    "type": "core::felt252"
                },
                {
                    "name": "symbol",
                    "type": "core::felt252"
                },
                {
                    "name": "erc20_token_contract",
                    "type": "core::starknet::contract_address::ContractAddress"
                }
            ]
        },
        {
            "type": "event",
            "name": "nftcontract::checkforworking::ShaboyGames::Event",
            "kind": "enum",
            "variants": []
        }
    ],
    address:"0x0295143c4af58c29088c0cbe87163f0c3f2dd7b1eb0877345f2f59b290aa4228"
    },
    ShaboySubscription:{
      "address":"0x058ef05164a42914B6f0Bf7BB9d97A1e80F92c4113dc5F0b8E573B03aFbd22a6",
      "abi": [
        {
            "type": "impl",
            "name": "ShaboySubscription",
            "interface_name": "contracts::subscription::IShaboyRegistry"
        },
        {
            "type": "enum",
            "name": "core::bool",
            "variants": [
                {
                    "name": "False",
                    "type": "()"
                },
                {
                    "name": "True",
                    "type": "()"
                }
            ]
        },
        {
            "type": "interface",
            "name": "contracts::subscription::IShaboyRegistry",
            "items": [
                {
                    "type": "function",
                    "name": "add_subscription",
                    "inputs": [
                        {
                            "name": "user",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "get_subscription",
                    "inputs": [
                        {
                            "name": "address",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::bool"
                        }
                    ],
                    "state_mutability": "view"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": [
                {
                    "name": "erc20_token_contract",
                    "type": "core::starknet::contract_address::ContractAddress"
                }
            ]
        },
        {
            "type": "event",
            "name": "contracts::subscription::ShaboySubscription::Event",
            "kind": "enum",
            "variants": []
        }
    ]
    },
    ShaboyGamesMinterRegistry:{
      "abi": [
        {
            "type": "impl",
            "name": "ShaboyGamesMinterRegistry",
            "interface_name": "nftcontract::storage::IShaboyRegistry"
        },
        {
            "type": "struct",
            "name": "core::integer::u256",
            "members": [
                {
                    "name": "low",
                    "type": "core::integer::u128"
                },
                {
                    "name": "high",
                    "type": "core::integer::u128"
                }
            ]
        },
        {
            "type": "interface",
            "name": "nftcontract::storage::IShaboyRegistry",
            "items": [
                {
                    "type": "function",
                    "name": "add_minter",
                    "inputs": [
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "minter",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "get_minter",
                    "inputs": [
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": []
        },
        {
            "type": "event",
            "name": "nftcontract::storage::ShaboyGamesMinterRegistry::Event",
            "kind": "enum",
            "variants": []
        }
    ],
    "address":"0x0189f950684dfb8833006c2c62d825a5f31fa30059dde2d7650a3e7a59f48c98"
    }
  },
  sepolia: {
    Eth: {
      address: universalEthAddress,
      abi: [
        {
          type: "impl",
          name: "ERC20Impl",
          interface_name: "openzeppelin::token::erc20::interface::IERC20",
        },
        {
          name: "openzeppelin::token::erc20::interface::IERC20",
          type: "interface",
          items: [
            {
              name: "name",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "symbol",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "decimals",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "total_supply",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "balance_of",
              type: "function",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "allowance",
              type: "function",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "transfer",
              type: "function",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              name: "transfer_from",
              type: "function",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              name: "approve",
              type: "function",
              inputs: [
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          name: "ERC20CamelOnlyImpl",
          type: "impl",
          interface_name:
            "openzeppelin::token::erc20::interface::IERC20CamelOnly",
        },
        {
          type: "interface",
          name: "openzeppelin::token::erc20::interface::IERC20CamelOnly",
          items: [
            {
              name: "totalSupply",
              type: "function",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "balanceOf",
              type: "function",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              name: "transferFrom",
              type: "function",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          kind: "struct",
          name: "openzeppelin::token::erc20_v070::erc20::ERC20::Transfer",
          type: "event",
          members: [
            {
              kind: "data",
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              kind: "data",
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              kind: "data",
              name: "value",
              type: "core::integer::u256",
            },
          ],
        },
        {
          kind: "enum",
          name: "openzeppelin::token::erc20_v070::erc20::ERC20::Event",
          type: "event",
          variants: [
            {
              kind: "nested",
              name: "Transfer",
              type: "openzeppelin::token::erc20_v070::erc20::ERC20::Transfer",
            },
          ],
        },
      ],
    },
    ShaboyGames:{
      abi: [
        {
            "type": "impl",
            "name": "ExternalImplERC721",
            "interface_name": "nftcontract::checkforworking::IERC721"
        },
        {
            "type": "struct",
            "name": "core::integer::u256",
            "members": [
                {
                    "name": "low",
                    "type": "core::integer::u128"
                },
                {
                    "name": "high",
                    "type": "core::integer::u128"
                }
            ]
        },
        {
            "type": "interface",
            "name": "nftcontract::checkforworking::IERC721",
            "items": [
                {
                    "type": "function",
                    "name": "name",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "symbol",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "balance_of",
                    "inputs": [
                        {
                            "name": "account",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "owner_of",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "get_counter_id",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "allowed_erc20_address",
                    "inputs": [],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "price_of_token_id",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::integer::u256"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "token_title",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::felt252"
                        }
                    ],
                    "state_mutability": "view"
                },
                {
                    "type": "function",
                    "name": "mint_multi",
                    "inputs": [
                        {
                            "name": "token_name",
                            "type": "core::felt252"
                        },
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "list",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "price",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "buy_nft",
                    "inputs": [
                        {
                            "name": "token_id",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "amount",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": [
                {
                    "name": "name",
                    "type": "core::felt252"
                },
                {
                    "name": "symbol",
                    "type": "core::felt252"
                },
                {
                    "name": "erc20_token_contract",
                    "type": "core::starknet::contract_address::ContractAddress"
                }
            ]
        },
        {
            "type": "event",
            "name": "nftcontract::checkforworking::ShaboyGames::Event",
            "kind": "enum",
            "variants": []
        }
    ],
    address:"0x0295143c4af58c29088c0cbe87163f0c3f2dd7b1eb0877345f2f59b290aa4228"
    },
    ShaboySubscription:{
      "address":"0x058ef05164a42914B6f0Bf7BB9d97A1e80F92c4113dc5F0b8E573B03aFbd22a6",
      "abi": [
        {
            "type": "impl",
            "name": "ShaboySubscription",
            "interface_name": "contracts::subscription::IShaboyRegistry"
        },
        {
            "type": "enum",
            "name": "core::bool",
            "variants": [
                {
                    "name": "False",
                    "type": "()"
                },
                {
                    "name": "True",
                    "type": "()"
                }
            ]
        },
        {
            "type": "interface",
            "name": "contracts::subscription::IShaboyRegistry",
            "items": [
                {
                    "type": "function",
                    "name": "add_subscription",
                    "inputs": [
                        {
                            "name": "user",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "get_subscription",
                    "inputs": [
                        {
                            "name": "address",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::bool"
                        }
                    ],
                    "state_mutability": "view"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": [
                {
                    "name": "erc20_token_contract",
                    "type": "core::starknet::contract_address::ContractAddress"
                }
            ]
        },
        {
            "type": "event",
            "name": "contracts::subscription::ShaboySubscription::Event",
            "kind": "enum",
            "variants": []
        }
    ]
    },
    ShaboyGamesMinterRegistry:{
      "abi": [
        {
            "type": "impl",
            "name": "ShaboyGamesMinterRegistry",
            "interface_name": "nftcontract::storage::IShaboyRegistry"
        },
        {
            "type": "struct",
            "name": "core::integer::u256",
            "members": [
                {
                    "name": "low",
                    "type": "core::integer::u128"
                },
                {
                    "name": "high",
                    "type": "core::integer::u128"
                }
            ]
        },
        {
            "type": "interface",
            "name": "nftcontract::storage::IShaboyRegistry",
            "items": [
                {
                    "type": "function",
                    "name": "add_minter",
                    "inputs": [
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        },
                        {
                            "name": "minter",
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "outputs": [],
                    "state_mutability": "external"
                },
                {
                    "type": "function",
                    "name": "get_minter",
                    "inputs": [
                        {
                            "name": "supply",
                            "type": "core::integer::u256"
                        }
                    ],
                    "outputs": [
                        {
                            "type": "core::starknet::contract_address::ContractAddress"
                        }
                    ],
                    "state_mutability": "view"
                }
            ]
        },
        {
            "type": "constructor",
            "name": "constructor",
            "inputs": []
        },
        {
            "type": "event",
            "name": "nftcontract::storage::ShaboyGamesMinterRegistry::Event",
            "kind": "enum",
            "variants": []
        }
    ],
    "address":"0x0189f950684dfb8833006c2c62d825a5f31fa30059dde2d7650a3e7a59f48c98"
    },
    
  },
} as const;

export default preDeployedContracts;
